### ISSUE TITLE
Editor Icon

### ISSUE THREAD

**Issue by bjmi** [mchr3k/jdeclipse-realign#1]
Could you provide an Icon for Editor extension (realignment.editor.jd.ide.eclipse)?
The default icon for e.g. text files is the same. Therefore it would be much more easier to distinguish java decompiled class from other files.

**Comment by mchr3k** [comment]
I can certainly add an icon. Do you have any suggestions about an icon which I should use?

**Comment by bjmi** [comment]
Not really, a good starting point may be
http://eclipse-icons.i24.cc/ovr16/jcu_obj.gif
or
http://eclipse-icons.i24.cc/ovr16/build_tab.gif

**Comment by mchr3k** [comment]
I've added the following icon: https://github.com/mchr3k/jdeclipse-realign/blob/master/icons/icon.png

**Comment by bjmi** [comment]
It's a great idea to invert colors. Updated via P2 and it look's good.
Thank you.
