### ISSUE TITLE
It tries to load *NUX library on Windows x64

### ISSUE THREAD

**Issue by lopotun** [mchr3k/jdeclipse-realign#10]
When I try to see decompiled class I get the following error:

An error has occurred. See error log for more details.
C:\eclipse\configuration\org.eclipse.osgi\bundles\75\1.cp\lib\linux\x86\libjd-eclipse.so: Can't load this .dll (machine code=0x101) on a AMD 64-bit platform

I run Eclipse Juno on Windows7 x64.

**Comment by mchr3k** [comment]
The library loading is handled by the core JD-Eclipse plugin: http://java.decompiler.free.fr/?q=jdeclipse
