### ISSUE TITLE
Make use of new '*.class without source' file association

### ISSUE THREAD

**Issue by peterox** [mchr3k/jdeclipse-realign#11]
Juno added a new file association of '*.class without source' which I associated with the JDEclipse 'Class File Editor' so that JDEclipse doesn't get in the road of jars with source attachments. This works really well except for the code alignment problem of JDEclipse. 

Then I found your great plugin but it seems that if I open a class file it still only opens in 'normal' JDEclipse editor not your realigned editor.

Please make it possible that the realigned editor is used when associated with '*.class without source'.

Keep up the good work

**Comment by mchr3k** [comment]
Unfortunately there isn't a good way for me to support this. I wrote about this on my blog: http://mchr3k-coding.blogspot.co.uk/2012/08/jd-eclipse-realign-source-lifetime.html

**Comment by mchr3k** [comment]
Issue 12 is now tracking this overall enhancement.
