### ISSUE TITLE
Download package

### ISSUE THREAD

**Issue by misery** [mchr3k/jdeclipse-realign#13]
I'm missing a package (.tar.gz or .zip) that can be downloaded and placed (extracted) manually to eclipse plugins folder. We cannot add the update site to our eclipse because we habe no internet connection on our development computers.

Is it possible to provide a separate package?

**Comment by mchr3k** [comment]
http://mchr3k-eclipse.appspot.com/files/mchr3k-eclipse.zip is a compressed copy of my update site.

**Comment by misery** [comment]
Thank you very much! :-)
Well.... is it possible to update this package for every new version?

**Comment by mchr3k** [comment]
I intended to do this manually but it seems I forgot on my very next release. I will come up with a way of automating this.

**Comment by mchr3k** [comment]
I have manually updated the package for now.

**Comment by sdaseem** [comment]
I am getting the following while trying to install this plugin: 
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: osgi.bundle,beaver,3.0.0.1346444146.
MD5 hash is not as expected. Expected: 6e2090b3077c61e6468586ecc7c08329 and found 51072a6fd308dc6ee5226f330a4d046d.

This happens irrespective of the fact that I am using manual or online install. 
Running Eclipse Juno
What can the reason be?

**Comment by mchr3k** [comment]
Your Eclipse is trying to get another plugin at the same time. "beaver" isn't one which I recognize - I don't know what to suggest to solve your problem. I don't think this has anything to do with my update site.

**Comment by movcale** [comment]
See here 
http://stackoverflow.com/questions/1371176/downloading-eclipse-plug-in-update-sites-for-offline-installation

I have install that plug-in without internet connection. Just archive all inside "mirror" dir into zip file and make "Install from archive" in Eclipse

Windows bat file might be:

set JAVA_HOME=C:\work\jdk
set ECLIPSE_HOME=C:\work\Eclipse
set FROM_URL=http://mchr3k-eclipse.appspot.com
set TO_DIR=.\mirror
%JAVA_HOME%\bin\java -jar %ECLIPSE_HOME%\plugins\org.eclipse.equinox.launcher_[YOUR VERSION].jar -application org.eclipse.update.core.standaloneUpdate -command mirror -from %FROM_URL% -to %TO_DIR%
