### ISSUE TITLE
realign doesn't work if line numbers turned off

### ISSUE THREAD

**Issue by codeturner** [mchr3k/jdeclipse-realign#17]
After turning off 'Display line numbers' in Preferences > Java > Decompiler, plugin doesn't realign the source to match line numbers.

Since I already have line numbers turned on in Eclipse (Preferences > General > Editors > Text Editors), I really don't need them showing up twice.

**Comment by mchr3k** [comment]
The line numbers are generated in the initial decompilation process and used during realignment. 

I like this idea - I'll add an option at some point to enable stripping of this line number information.

**Comment by mchr3k** [comment]
I have fixed this in version 1.1.2. See http://mchr3k.github.com/jdeclipse-realign/ for more details.
