### ISSUE TITLE
Batch processing of decompiled sources packed in a Zip/Jar file

### ISSUE THREAD

**Issue by ikaygorodov** [mchr3k/jdeclipse-realign#19]
Please return this function, it was not working as it supposed to be and maybe it should be sepparated in cmd util, but a lot of people really need it.

**Comment by mchr3k** [comment]
Can you please provide more details about the function which you are looking for? I'm not sure what you think is missing.

**Comment by ikaygorodov** [comment]
Of course, I'm talking about src\jd\ide\eclipse\realignment\dialogs\BatchDecompilingDialog.java and
src\jd\ide\eclipse\realignment\editors\BatchProcessing.java that was removed on 7/6/2012

I have plans to make a smal cmd util using this code, but from my point of view it would be greate to have this functionality inside this plugin also.

**Comment by mchr3k** [comment]
That batch processing function didn't seem like it was strongly related to the rest of the Eclipse plugin code so I removed it. If you want to use it you will need to fork this project or download http://sourceforge.net/projects/realignmentjd/ which I originally forked.

**Comment by ikaygorodov** [comment]
ok. I agree. Thanks for keeping an Eclipse plugin in good shape. =)
