### ISSUE TITLE
Open Class With" menu option doesn't appear in "Project Explorer" View

### ISSUE THREAD

**Issue by youngm** [mchr3k/jdeclipse-realign#5]
Thanks for the great plugin.

I noticed that the Open Class With option doesn't appear when right clicking on .class files in the "Project Explorer" View.

It would be great if it could appear there too.

**Comment by mchr3k** [comment]
Thanks for raising this. I spotted the same problem myself but forgot about it. I'll probably fix this in the next release as it _should_ be fairly straightforward.

**Comment by ghost** [comment]
Great, glad i found this, i thought i was doing something wrong :-)

**Comment by mchr3k** [comment]
This should now be fixed in release 1.0.9.
