### ISSUE TITLE
Improve discoverability

### ISSUE THREAD

**Issue by mchr3k** [mchr3k/jdeclipse-realign#6]
When there in no source available the Class File Viewer displays a button promoting for source to be attached. It is not obvious that right clicking the class in the Package Explorer view allows decompiled source to be enabled. It would be better if the Class File Viewer included a button or some other indication that Decompiled Source could be enabled.

**Comment by youngm** [comment]
I don't know if any of these are any easier but I think something like this could work:
- Perhaps it is possible to just add a preference that can enable decompilation of classes without source attached by default?
- Maven Eclipse's JDT plugin uses the "org.eclipse.ui.editorActions" extension point with its "org.eclipse.m2e.jdt.internal.DownloadSourcesActionDelegate" class to automatically download sources when a class in a dependency without sources is opened.  Perhaps you could somehow use this same extension point to help make the user aware of the option to decompile?

**Comment by mchr3k** [comment]
That sounds promising. Thanks for the reference - I will look into it.

**Comment by kwin** [comment]
Having the decompilation enabled by default for all classes without a source attached, would definitely be good. Please add this, since this was possible with the old approach of having a dedicated decompilation class file viewer associated with class files.

**Comment by mchr3k** [comment]
It was possible with the old approach but the old approach also caused some bugged behaviour. It is on my todo list to come up with a new way to make this work properly :)

**Comment by mchr3k** [comment]
For my own reference:

http://git.eclipse.org/c/m2e/m2e-core.git/tree/org.eclipse.m2e.jdt/plugin.xml

```
<extension point="org.eclipse.ui.editorActions">
   <editorContribution id="org.eclipse.m2e.jdt.downloadSourcesContribution"
                       targetID="org.eclipse.jdt.ui.ClassFileEditor">
      <action id="org.eclipse.m2e.jdt.downloadSourcesAction"
           class="org.eclipse.m2e.jdt.internal.DownloadSourcesActionDelegate"
           label="%action.label" style="push"/>
   </editorContribution>
   <editorContribution id="org.eclipse.m2e.jdt.downloadSourcesContribution_38"
                       targetID="org.eclipse.jdt.ui.ClassFileEditorNoSource">
      <action id="org.eclipse.m2e.jdt.downloadSourcesAction"
           class="org.eclipse.m2e.jdt.internal.DownloadSourcesActionDelegate"
           label="%action.label" style="push"/>
   </editorContribution>
</extension>
```

http://git.eclipse.org/c/m2e/m2e-core.git/tree/org.eclipse.m2e.jdt/src/org/eclipse/m2e/jdt/internal/DownloadSourcesActionDelegate.java

If no source is attached a download is scheduled.

My plan is to implement something similar to automatically attach decompiled source. This will likely be controlled by a preferences page.

**Comment by youngm** [comment]
I think that would work great!  As long as it doesn't interfere with Maven's attaching when Maven can get the source.

**Comment by mchr3k** [comment]
You make an excellent point. I will make sure that whatever I implement interacts nicely with the Maven plugin. 

I suspect that the result will be that classes without source will open with decompiled source first and then be updated to use real source when/if the Maven download completes.

**Comment by youngm** [comment]
That would be fine if that is the case.

**Comment by mchr3k** [comment]
I've added toolbar buttons which should make discoverability easier. For details: http://mchr3k.github.com/jdeclipse-realign/

Decompiling by default for classes without source would be good but I haven't worked out how to do this yet. I've opened a new issue to cover fixing that at some point: https://github.com/mchr3k/jdeclipse-realign/issues/12
