### ISSUE TITLE
Class not decompiled if bundle has incomplete source attached

### ISSUE THREAD

**Issue by youngm** [mchr3k/jdeclipse-realign#7]
Occasionally I find myself viewing a class that is part of a jar that has source attached but no source for the class I am currently viewing.  In this case I am unaware of a way to enable decompilation for this class.

For example, the Sun JDK has the class "com.sun.media.sound.SunCodec"  It is part of the rt.jar but the source is not include in the src.zip file.  When I view this class in eclipse it would be nice if it were possible to see a decompilation of it.

**Comment by mchr3k** [comment]
I suspect this will be tricky to fix as I think Eclipse only allows a single source attachment for a jar. I don't think there is any support for having source for different parts of a jar provided from different sources. 

I will take a look and see if I can find any way of achieving this. 

In the mean time I think you will have to switch between attached source and decompiled source for the entire jar. I am hoping to make this switching easier in future.

**Comment by scheung38** [comment]
Hi,

Can you show people how to integrate jdeclipse-realign into eclipse? Not sure how to add it into it. Thanks

**Comment by mchr3k** [comment]
The UI for enabling/disabling decompiled source is shown on this page: http://mchr3k.github.com/jdeclipse-realign/

To install the plugin:
- Within Eclipse, open Help -> Install New Software
- Enter the following URL: http://mchr3k-eclipse.appspot.com/
- Select the "Java Decompiler Eclipse Plug-in" category
- Click Next and continue until the plugin has been installed

**Comment by scheung38** [comment]
Thanks for quick reply, I did as you mentioned, and restarted eclipse and now it is in the list of Referenced Libraries, but I still cannot see how to automatically convert class files to .java file? When I right click on the class files I do not see any of the options to decompile?

**Comment by mchr3k** [comment]
What version of Eclipse are you using? What exactly do you mean by the "Refenced Libraries"? Which View are you using when you right click on a class file? Can you post a screenshot somewhere of the context menu which doesn't include the expected entries?

**Comment by mchr3k** [comment]
@youngm I have just released version 1.1.1 which makes it much easier to quickly switch between attached/decompiled source. This still has to happen at the scope of an entire jar but hopefully this improves your original issue.

I don't think I can easily do any better so I am closing this issue.

**Comment by youngm** [comment]
Excellent!  Thanks @mchr3k.  I will try it out first thing Monday.
