### ISSUE TITLE
Attach Source -> Decompiled Source for multiple jars not working

### ISSUE THREAD

**Issue by persal** [mchr3k/jdeclipse-realign#8]
When selecting multiple jar files in the Package explorer under for example "Referenced Libraries" the right-click and Attach Source-> Decompiled Source have no effect. It seem to work, byt when opening up a class the lines are not aligned.

When right-clicking on each of the jar files separately it works.

Suggestion, either give a warning that multiple jars cannot be selected at once, or even better, make it work for all the selected jar files.

Great extension of the JD plugin btw.

**Comment by mchr3k** [comment]
This should now work. Details can be seen here: http://mchr3k.github.com/jdeclipse-realign/
